### ISSUE TITLE
Colaboration

### ISSUE THREAD

**Issue by ghost** [misams/BAT#15]
Hi Misams,

i have some ground-braking code proposals for you.
Please add me as member so i can (try) to push my changes.
![image](https://user-images.githubusercontent.com/58887942/153172641-26a78e49-167a-4021-9795-d72cb5e2ece1.png)

KR

**Comment by misams** [comment]
Hi,

if you fork BAT to your repository - as you did - you should be able to modify and push with no problem in your forked version of BAT. After modifying you should try a "Pull request" on my repo :-)

LG
